# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Override specific Omarchy defaults
source = ~/.config/hypr/windows-override.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, class:qemu
# windowrule = workspace 1, class:obsidian

# DaVinci Resolve - Fix floating dialogs
#windowrulev2 = tag +drpopup, class:^(resolve)$, floating:1
#windowrulev2 = stayfocused, tag:drpopup
#windowrulev2 = bordersize 0, tag:drpopup
#windowrulev2 = noborder, tag:drpopup
#windowrulev2 = noshadow, tag:drpopup
#windowrulev2 = rounding 0, tag:drpopup
#windowrulev2 = opaque, tag:drpopup

# Toggle config flags dynamically
source = ~/.local/state/omarchy/toggles/hypr/*.conf
