# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows
    gaps_in = 1
    gaps_out = 1

    resize_on_border = true

    # Use master layout instead of dwindle
    # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 8
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

# Just dash of opacity by default
# windowrule = opacity 0.99 0.95, class:.*

# Animations
animation = workspaces, 1, 2, default, slidefadevert 100%
