#!/usr/bin/env bash
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# Setup some global vars
grep=""
dry_run="0"

while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry_run="1"
    else
        grep="$1"
    fi
    shift
done

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

log "RUN: grep: $grep"

cmds_dir=`find $script_dir/cmds -mindepth 1 -maxdepth 1 -executable`

log $cmds_dir

for s in $cmds_dir; do
    if basename $s | grep -vq "$grep"; then
#        log "grep \"$grep\" filtered out $s"
        continue
    fi

    if [[ $dry_run == "0" ]]; then
        log "executing $s"
        $s
    else
        log "[DRY_RUN] Skipping $s"
    fi
done
