#!/usr/bin/env bash

# Stow the configuration files
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

script_dir=`pwd | sed 's#dotfiles/cmds/logo.*##g'`

script_dir="$script_dir/configs/logo.txt"

cp $script_dir ~/.local/share/omarchy/
